Games Table

Summary:

    This table contains 74026 rows of games tracking teams home and away, goals scored by each, competition information, stadium attendance and referee information

Insights:

This table is essential for calculating club records like goals and placement in various competitions. Referees and red card statitics might be fun to look into.

Cleaning Tasks:

drop  9 games with missing home and away ids unless found
fill home_club and away_club position with 100
fill home_club name and away_club name nulls with club id information
replace home and away club manager nulls with "missing"
replace attendance nulls with home club attendance avg
replace formation nulls with 0
replace aggregate nulls with 0

In [7]:
import pandas as pd
games_df = pd.read_csv('../data/raw/games.csv')
games_df.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2321027,L1,2013,1. Matchday,2013-08-11,33.0,41.0,3.0,3.0,8.0,...,Veltins-Arena,61973.0,Manuel Gräfe,https://www.transfermarkt.co.uk/fc-schalke-04_...,4-2-3-1,4-2-3-1,FC Schalke 04,Hamburger SV,3:3,domestic_league
1,2321033,L1,2013,1. Matchday,2013-08-10,23.0,86.0,0.0,1.0,13.0,...,EINTRACHT-Stadion,23000.0,Deniz Aytekin,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-3-1-2,Eintracht Braunschweig,Sportverein Werder Bremen von 1899,0:1,domestic_league
2,2321044,L1,2013,2. Matchday,2013-08-18,16.0,23.0,2.0,1.0,1.0,...,SIGNAL IDUNA PARK,80200.0,Peter Sippel,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,4-3-2-1,Borussia Dortmund,Eintracht Braunschweig,2:1,domestic_league
3,2321060,L1,2013,3. Matchday,2013-08-25,23.0,24.0,0.0,2.0,18.0,...,EINTRACHT-Stadion,23325.0,Wolfgang Stark,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-2-3-1,Eintracht Braunschweig,Eintracht Frankfurt Fußball AG,0:2,domestic_league
4,2321072,L1,2013,5. Matchday,2013-09-14,16.0,41.0,6.0,2.0,1.0,...,SIGNAL IDUNA PARK,80645.0,Tobias Welz,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,3-5-2,Borussia Dortmund,Hamburger SV,6:2,domestic_league

In [2]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74026 entries, 0 to 74025
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 74026 non-null  int64
 1   competition_id          74026 non-null  object
 2   season                  74026 non-null  int64
 3   round                   74026 non-null  object
 4   date                    74026 non-null  object
 5   home_club_id            74017 non-null  float64
 6   away_club_id            74017 non-null  float64
 7   home_club_goals         74014 non-null  float64
 8   away_club_goals         74014 non-null  float64
 9   home_club_position      51559 non-null  float64
 10  away_club_position      51559 non-null  float64
 11  home_club_manager_name  73198 non-null  object
 12  away_club_manager_name  73198 non-null  object
 13  stadium                 73776 non-null  object
 14  attendance              64078 non-null  float64
 15  referee                 73374 non-null  object
 16  url                     74026 non-null  object
 17  home_club_formation     67051 non-null  object
 18  away_club_formation     67220 non-null  object
 19  home_club_name          61176 non-null  object
 20  away_club_name          62571 non-null  object
 21  aggregate               74014 non-null  object
 22  competition_type        74026 non-null  object
dtypes: float64(7), int64(2), object(14)
memory usage: 13.0+ MB

In [3]:
games_df.describe().round(3)

,game_id,season,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,attendance
count,74026.000,74026.000,74017.000,74017.000,74014.000,74014.000,51559.000,51559.000,64078.000
mean,3165279.501,2017.982,5324.385,4811.172,1.600,1.332,9.274,9.453,18346.865
std,667940.774,3.740,31142.913,30685.939,1.433,1.371,5.298,5.318,17950.346
min,2211607.000,2012.000,1.000,2.000,0.000,0.000,1.000,1.000,1.000
25%,2587785.000,2015.000,354.000,347.000,1.000,0.000,5.000,5.000,4400.000
50%,3080342.500,2018.000,995.000,987.000,1.000,1.000,9.000,9.000,12400.000
75%,3646235.750,2021.000,3209.000,3037.000,2.000,2.000,14.000,14.000,26718.500
max,4572898.000,2024.000,4506872.000,4506873.000,17.000,19.000,21.000,21.000,99354.000

In [4]:
games_df.isnull().sum()

game_id                       0
competition_id                0
season                        0
round                         0
date                          0
home_club_id                  9
away_club_id                  9
home_club_goals              12
away_club_goals              12
home_club_position        22467
away_club_position        22467
home_club_manager_name      828
away_club_manager_name      828
stadium                     250
attendance                 9948
referee                     652
url                           0
home_club_formation        6975
away_club_formation        6806
home_club_name            12850
away_club_name            11455
aggregate                    12
competition_type              0
dtype: int64

In [5]:
games_df.duplicated().sum()

np.int64(0)

In [9]:
null_id_df = games_df[games_df['home_club_id'].isnull()]
null_id_df.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
71278,4506869,KLUB,2024,Quarter-Finals,2025-07-05,NaN,NaN,NaN,NaN,NaN,...,Lincoln Financial Field,NaN,NaN,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,NaN,NaN,NaN,other
71327,4506861,KLUB,2024,Round of 16,2025-06-28,NaN,NaN,NaN,NaN,NaN,...,Bank of America Stadium,NaN,NaN,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,NaN,NaN,NaN,other
71328,4506862,KLUB,2024,Round of 16,2025-06-29,NaN,NaN,NaN,NaN,NaN,...,Mercedes-Benz Stadium,NaN,NaN,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,NaN,NaN,NaN,other
71354,4506864,KLUB,2024,Round of 16,2025-06-30,NaN,NaN,NaN,NaN,NaN,...,Bank of America Stadium,NaN,NaN,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,NaN,NaN,NaN,other
71355,4506867,KLUB,2024,Round of 16,2025-07-02,NaN,NaN,NaN,NaN,NaN,...,Mercedes-Benz Stadium,NaN,NaN,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,NaN,NaN,NaN,other